"use client";

import { useMemo, useState } from "react";

type SortKey = "model" | "quality" | "latency" | "cost" | "success" | "retries" | "notes";
type SortDirection = "asc" | "desc";
type SortState = {
  key: SortKey;
  direction: SortDirection;
};

type ModelEvalRow = {
  id: string;
  label: string;
  provider: string;
  evaluated: boolean;
  questionCount: number;
  averageQuality: number | null;
  averageHeuristicQuality?: number | null;
  averageLlmQuality?: number | null;
  averageSecondJudgeQuality?: number | null;
  averageLatencyMs: number | null;
  latencyP50Ms: number | null;
  latencyP90Ms: number | null;
  averageCostUsd: number | null;
  successRate: number | null;
  retryRate: number | null;
  failureCount: number | null;
  dimensions: Record<string, number> | null;
  notes: string;
};

export type ModelEvalReport = {
  schemaVersion: number;
  status: "not_run" | "complete" | "partial";
  generatedAt: string | null;
  questionSet: {
    path: string;
    count: number;
  };
  summary: {
    bestQualityModelId: string | null;
    fastestModelId: string | null;
    lowestCostModelId: string | null;
    notes: string[];
  };
  evaluation?: {
    qualityMethod: string;
    llmJudgeModel: string | null;
    llmJudgeWeight: number;
    secondJudgeModel?: string | null;
    secondJudgeMode?: "off" | "auto" | "always";
    estimatedSpendUsd: number | null;
    budgetUsd: number | null;
  };
  models: ModelEvalRow[];
};

const sortOptions: Array<{ key: SortKey; label: string; hint: string; defaultDirection: SortDirection }> = [
  { key: "quality", label: "Quality", hint: "Highest average score first", defaultDirection: "desc" },
  { key: "latency", label: "Speed", hint: "Lowest average latency first", defaultDirection: "asc" },
  { key: "cost", label: "Cost", hint: "Lowest average cost first", defaultDirection: "asc" }
];

const defaultSortDirections: Record<SortKey, SortDirection> = {
  model: "asc",
  quality: "desc",
  latency: "asc",
  cost: "asc",
  success: "desc",
  retries: "asc",
  notes: "asc"
};

export function ModelQualityReport({ report }: { report: ModelEvalReport }) {
  const [sort, setSort] = useState<SortState>({ key: "quality", direction: "desc" });

  const sortedModels = useMemo(() => {
    return [...report.models].sort((left, right) => compareModels(left, right, sort));
  }, [report.models, sort]);

  const updateSort = (key: SortKey) => {
    setSort((current) => {
      if (current.key === key) {
        return { key, direction: current.direction === "asc" ? "desc" : "asc" };
      }
      return { key, direction: defaultSortDirections[key] };
    });
  };

  return (
    <div className="mx-auto w-full max-w-6xl px-4 py-6 sm:py-10">
      <header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <a href="/" className="text-sm font-black text-pond/70 underline-offset-4 transition hover:text-pond hover:underline">
            Back to Debatefrog
          </a>
          <h1 className="mt-5 max-w-3xl text-4xl font-black leading-[1.05] text-pond sm:text-6xl">
            Model report
          </h1>
          <p className="mt-4 max-w-3xl text-lg leading-relaxed text-ink/70">
            Quarterly evaluation results for the curated models Debatefrog can use.
          </p>
        </div>
        <div className="rounded-2xl border border-mud/15 bg-panel/90 px-4 py-3 shadow-lily">
          <div className="text-xs font-black uppercase tracking-wide text-mud/70">Last evaluated</div>
          <div className="mt-1 text-lg font-black text-pond">
            {report.generatedAt ? formatDate(report.generatedAt) : "Not run yet"}
          </div>
        </div>
      </header>

      <section className="mt-8 grid gap-3 sm:grid-cols-3">
        <SummaryCard label="Best quality" value={lookupModelLabel(report, report.summary.bestQualityModelId)} />
        <SummaryCard label="Fastest response" value={lookupModelLabel(report, report.summary.fastestModelId)} />
        <SummaryCard label="Lowest cost" value={lookupModelLabel(report, report.summary.lowestCostModelId)} />
      </section>

      {report.status === "not_run" ? (
        <section className="mt-6 rounded-2xl border border-sun/40 bg-cream/80 p-5 shadow-lily">
          <h2 className="text-xl font-black text-pond">Evaluation waiting to run</h2>
          <p className="mt-2 max-w-3xl text-sm leading-relaxed text-ink/70">
            This page is wired up, but real quality, latency, and cost numbers are generated by the offline evaluator.
            Run <code className="rounded bg-white/70 px-1.5 py-0.5 font-bold">npm run eval:debatefrog-models</code> from the repo root when you want to refresh the quarterly report.
          </p>
        </section>
      ) : null}

      {report.status === "partial" ? (
        <section className="mt-6 rounded-2xl border border-berry/30 bg-cream/90 p-5 shadow-lily">
          <h2 className="text-xl font-black text-pond">Partial evaluation</h2>
          <p className="mt-2 max-w-3xl text-sm leading-relaxed text-ink/70">
            Some models were not scored because this run stopped after the AI provider quota limit was reached.
            Sorts and summary cards use successful model runs only.
          </p>
        </section>
      ) : null}

      <section className="mt-6 rounded-2xl border border-mud/15 bg-panel/90 p-4 shadow-lily">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h2 className="text-2xl font-black text-pond">Curated models</h2>
            <p className="mt-1 text-sm text-ink/60">
              {report.questionSet.count} evaluation questions. Latency is an average from this run, with p50/p90 shown because response speed varies.
            </p>
            {report.evaluation ? (
              <p className="mt-1 text-xs text-ink/50">
                {qualityMethodCopy(report.evaluation)}
              </p>
            ) : null}
          </div>
          <div className="flex flex-wrap gap-2">
            {sortOptions.map((option) => (
              <button
                key={option.key}
                type="button"
                onClick={() => updateSort(option.key)}
                title={option.hint}
                className={`rounded-full px-4 py-2 text-sm font-black transition ${
                  sort.key === option.key
                    ? "bg-pond text-white shadow-pop"
                    : "bg-cream text-pond hover:bg-mint"
                }`}
              >
                {option.label}{sort.key === option.key ? ` ${sort.direction}` : ""}
              </button>
            ))}
          </div>
        </div>

        <div className="mt-4 overflow-x-auto">
          <table className="w-full min-w-[820px] border-separate border-spacing-y-2 text-left">
            <thead>
              <tr className="text-xs uppercase tracking-wide text-mud/70">
                <SortableHeader label="Model" sortKey="model" sort={sort} onSort={updateSort} />
                <SortableHeader label="Quality" sortKey="quality" sort={sort} onSort={updateSort} />
                <SortableHeader label="Latency" sortKey="latency" sort={sort} onSort={updateSort} />
                <SortableHeader label="Avg cost" sortKey="cost" sort={sort} onSort={updateSort} />
                <SortableHeader label="Success" sortKey="success" sort={sort} onSort={updateSort} />
                <SortableHeader label="Retries" sortKey="retries" sort={sort} onSort={updateSort} />
                <SortableHeader label="Notes" sortKey="notes" sort={sort} onSort={updateSort} />
              </tr>
            </thead>
            <tbody>
              {sortedModels.map((model) => (
                <tr key={model.id} className="bg-white/65 text-sm shadow-sm">
                  <td className="rounded-l-xl px-3 py-3">
                    <div className="font-black text-pond">{model.label}</div>
                    <div className="mt-0.5 text-xs text-ink/50">
                      {model.id}
                      {!model.evaluated ? <span className="ml-2 font-black text-berry">not evaluated</span> : null}
                    </div>
                  </td>
                  <td className="px-3 py-3 font-black text-ink">
                    <div>{formatScore(model.averageQuality)}</div>
                    {model.averageLlmQuality !== undefined || model.averageHeuristicQuality !== undefined ? (
                      <div className="mt-0.5 text-xs font-normal text-ink/45">
                        LLM {formatScore(model.averageLlmQuality ?? null)} · rules {formatScore(model.averageHeuristicQuality ?? null)}
                      </div>
                    ) : null}
                    {typeof model.averageSecondJudgeQuality === "number" ? (
                      <div className="mt-0.5 text-xs font-normal text-ink/45">
                        second opinion {formatScore(model.averageSecondJudgeQuality)}
                      </div>
                    ) : null}
                  </td>
                  <td className="px-3 py-3 text-ink/75">
                    <div>{formatLatency(model.averageLatencyMs)} avg</div>
                    <div className="mt-0.5 text-xs text-ink/45">
                      p50 {formatLatency(model.latencyP50Ms)} · p90 {formatLatency(model.latencyP90Ms)}
                    </div>
                  </td>
                  <td className="px-3 py-3 text-ink/75">{formatCost(model.averageCostUsd)}</td>
                  <td className="px-3 py-3 text-ink/75">{formatPercent(model.successRate)}</td>
                  <td className="px-3 py-3 text-ink/75">{formatPercent(model.retryRate)}</td>
                  <td className="rounded-r-xl px-3 py-3 text-ink/60">{model.notes}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
}

function SortableHeader({
  label,
  sortKey,
  sort,
  onSort
}: {
  label: string;
  sortKey: SortKey;
  sort: SortState;
  onSort: (key: SortKey) => void;
}) {
  const active = sort.key === sortKey;
  return (
    <th className="px-3 py-2">
      <button
        type="button"
        onClick={() => onSort(sortKey)}
        className={`flex items-center gap-1 rounded-md py-1 text-left font-black uppercase tracking-wide transition ${
          active ? "text-pond" : "text-mud/70 hover:text-pond"
        }`}
      >
        <span>{label}</span>
        {active ? <span className="text-[10px] normal-case tracking-normal">{sort.direction}</span> : null}
      </button>
    </th>
  );
}

function qualityMethodCopy(evaluation: NonNullable<ModelEvalReport["evaluation"]>) {
  const primaryJudge = evaluation.llmJudgeModel
    ? ` with ${labelForModelId(evaluation.llmJudgeModel)} as the primary evaluation judge`
    : "";
  const secondJudge = evaluation.secondJudgeModel && evaluation.secondJudgeMode !== "off"
    ? ` and ${labelForModelId(evaluation.secondJudgeModel)} for ${evaluation.secondJudgeMode} second opinions`
    : "";
  return `Quality uses ${evaluation.qualityMethod}${primaryJudge}${secondJudge}.`;
}

function SummaryCard({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-2xl border border-mud/15 bg-panel/90 p-4 shadow-lily">
      <div className="text-xs font-black uppercase tracking-wide text-mud/70">{label}</div>
      <div className="mt-2 text-xl font-black text-pond">{value}</div>
    </div>
  );
}

function compareModels(left: ModelEvalRow, right: ModelEvalRow, sort: SortState) {
  if (sort.key !== "model" && sort.key !== "notes") {
    const scoredComparison = compareScoredRows(left, right);
    if (scoredComparison !== 0) return scoredComparison;
  }

  switch (sort.key) {
    case "model":
      return compareStrings(left.label, right.label, sort.direction);
    case "quality":
      return compareNullableNumbers(left.averageQuality, right.averageQuality, sort.direction);
    case "latency":
      return compareNullableNumbers(left.averageLatencyMs, right.averageLatencyMs, sort.direction);
    case "cost":
      return compareNullableNumbers(left.averageCostUsd, right.averageCostUsd, sort.direction);
    case "success":
      return compareNullableNumbers(left.successRate, right.successRate, sort.direction);
    case "retries":
      return compareNullableNumbers(left.retryRate, right.retryRate, sort.direction);
    case "notes":
      return compareStrings(left.notes, right.notes, sort.direction);
  }
}

function compareScoredRows(left: ModelEvalRow, right: ModelEvalRow) {
  const leftScored = left.averageQuality !== null || left.averageLatencyMs !== null || left.averageCostUsd !== null;
  const rightScored = right.averageQuality !== null || right.averageLatencyMs !== null || right.averageCostUsd !== null;
  if (leftScored === rightScored) return 0;
  return leftScored ? -1 : 1;
}

function compareNullableNumbers(left: number | null, right: number | null, direction: SortDirection) {
  if (left === null && right === null) return 0;
  if (left === null) return 1;
  if (right === null) return -1;
  const diff = left - right;
  return direction === "asc" ? diff : -diff;
}

function compareStrings(left: string, right: string, direction: SortDirection) {
  const diff = left.localeCompare(right);
  return direction === "asc" ? diff : -diff;
}

function lookupModelLabel(report: ModelEvalReport, id: string | null) {
  if (!id) return "Not run yet";
  return report.models.find((model) => model.id === id)?.label ?? id;
}

function labelForModelId(id: string) {
  return id
    .split("/")
    .pop()!
    .replace(/[-_]+/g, " ")
    .replace(/\b\w/g, (letter) => letter.toUpperCase())
    .replace(/\bGpt\b/g, "GPT");
}

function formatDate(value: string) {
  return new Intl.DateTimeFormat(undefined, {
    dateStyle: "medium",
    timeStyle: "short"
  }).format(new Date(value));
}

function formatScore(value: number | null) {
  return value === null ? "Not scored" : `${Math.round(value)}/100`;
}

function formatLatency(value: number | null) {
  if (value === null) return "Not measured";
  if (value < 1000) return `${Math.round(value)} ms`;
  return `${(value / 1000).toFixed(value < 10000 ? 1 : 0)} s`;
}

function formatCost(value: number | null) {
  return value === null ? "Not measured" : `$${value.toFixed(5)}`;
}

function formatPercent(value: number | null) {
  return value === null ? "Not measured" : `${Math.round(value * 100)}%`;
}
